### PR TITLE
Some extra checks to prevent invalid entities from being copied

### PR DESCRIPTION
**Pull request by thegrb93**
For https://github.com/wiremod/advdupe2/issues/84

### CODE REVIEW

**Comment by thegrb93** [comment]
Bump

**Comment by AbigailBuccaneer** [comment]
Would be nice to have the common functionality of `if ent.DoNotDuplicate or not IsValid(ent:GetPhysicsObject()) or not duplicator.IsAllowed(ent:GetClass()) then return false end` in a separate function - I think there have been other issues where we didn't support one of these things in one place and so allowed some entities that shouldn't be duplicated.

**Comment by thegrb93** [comment]
This only applies to copying and PlayerCanDupeCPPI and PlayerCanDupeTool are the common functionality for copying.

**Comment by thegrb93** [comment]
Bump for this.

**Pull request merged**
