### PR TITLE
Make language actually working

### PR DESCRIPTION
**Pull request by Blueberryy**
+extra Russian translation :p

### CODE REVIEW

**Comment by thegrb93** [comment]
I think we'll need a resource.AddWorkshop for this now so the new files get acquired.

**Comment by thegrb93** [comment]
What if we instead do
```lua
if GetConvarString("whatever_language_convar_is")=="ru" then
    language.Add("...","russian")
else
    language.Add("...","english")
end
```

**Review by thegrb93 — CHANGES_REQUESTED** [review]
Use `GetConvarString("gmod_language")` instead of .properties files.

**Comment by Divran** [comment]
I don't know what the proper way is to handle language in gmod, but what's wrong with `.properties` files?

**Comment by thegrb93** [comment]
Client has to download them or the tool's text is all broken.

**Comment by Divran** [comment]
and they're not auto downloaded? or alternatively is there a way to make them download such as with `AddCSLuaFile` for lua files?

**Comment by thegrb93** [comment]
You'd need to resource.AddSingleFile, yeah. It's better just to do my suggestion since then you don't need to download.

**Comment by Divran** [comment]
Are you suggesting we put that if statement in the tool files? because if we put it in a different file then that file would need to be downloaded with `AddCSLuaFile`. And if we put it in the tool file, then it'll be super ugly later if we want to add more than two languages.

**Comment by thegrb93** [comment]
Yes, and it wouldn't be that ugly.

**Comment by Divran** [comment]
idk, several giant elseif chains spread out over multiple tool files is a whole lot uglier than 1 single 
`resource.AddSingleFile("/languages/"..GetConvarString("gmod_language")..".properties")`
or even `AddCSLuaFile("/languages/"..GetConvarString("gmod_language")..".lua")`
somewhere in this file <https://github.com/wiremod/advdupe2/blob/master/lua/autorun/server/advdupe2_sv_init.lua>

**Comment by thegrb93** [comment]
The server doesn't know what language the client has selected so that wouldn't work.

**Comment by Divran** [comment]
oh right, rip

**Comment by thegrb93** [comment]
@Blueberryy can you implement the suggested changes? Also don't escape the characters. Lua supports cyrillic. Otherwise this pr will just become stale and close.

**Pull request closed without merging**
