### PR TITLE
Update SavePositions to use physobject positions

### PR DESCRIPTION
**Pull request by thegrb93**
Potentially fixes: #331

### CODE REVIEW

**Comment by thegrb93** [comment]
Another solution I might try is rebuilding the entity's bones so that (hopefully) it syncs with its physobj and then this code will be a lot cleaner.

**Comment by TitusStudiosMediaGroup** [comment]
Works on my client, works both for tool and SEnt axis

**Comment by thegrb93** [comment]
Thanks. Will merge if I can't find a way to sync entity and physobj.

**Comment by thegrb93** [comment]
Looks like wake() doesn't work until next frame, so this is the best solution.

**Pull request merged**
