### PR TITLE
World copy

### PR DESCRIPTION
**Pull request by thegrb93**
Remade pr because git

Made right clicking world select-all/deselect-all and cleaned up the code a lot. Finally no sneaky e2s or other player's shit getting included with a dupe since you can select everything you own just by right clicking the world.

### CODE REVIEW

**Comment by Divran** [comment]
Did you make sure area copy only copies entities you own, even if the other
player has added you to PP? (Perhaps make a checkbox to allow you to select
other people's stuff if someone still wants to)

**Comment by thegrb93** [comment]
Yeah it only selects what you own. If someone wants a checkbox to be able to select everything he can tool we can do another pr for that. Unnecessary imo though and might be hard to filter out map entities.

**Comment by Divran** [comment]
nah it won't be hard to filter out map entities, you just run a PP check as
usual instead of owner only.

**Comment by thegrb93** [comment]
If I add the new checkbox, should I change the area copy to only copy your own entities unless the box is checked too?

**Comment by thegrb93** [comment]
This contains commits from my other pr because I didn't want to deal with conflicts, but they should go invisible once that pr is merged. This adds a checkbox that lets you toggle whether you want to only copy your own props or any prop you can touch.

**Comment by thegrb93** [comment]
Tested on my server. No problems.

**Comment by Divran** [comment]
And the default is only your own props, right?

**Comment by thegrb93** [comment]
Yeah

**Comment by Divran** [comment]
ok then, fine by me to merge

:+1:

**Comment by thegrb93** [comment]
Still no problems.

**Pull request merged**
