### PR TITLE
Refactored copying

### PR DESCRIPTION
**Pull request by thegrb93**
Made right clicking world select-all/deselect-all and cleaned up the code a lot. Finally no sneaky e2s or other player's shit getting included with a dupe since you can select everything you own just by right clicking the world.

I'll test this out on my server for a while and will fix any problems that come up.

### CODE REVIEW

**Comment by thegrb93** [comment]
Oh yeah, also I wanted to have the toolgun do its normal sound effect when clearing the dupe, but it won't do it even though the RightClick hook is returning true. What's the problem?

**Comment by thegrb93** [comment]
>Oh yeah, also I wanted to have the toolgun do its normal sound effect when clearing the dupe, but it won't do it even though the RightClick hook is returning true. What's the problem?

Nvm, I found the server and client RightClick/LeftClick are different. I'll try to fix that.

**Comment by thegrb93** [comment]
There we go. Much better.

**Comment by Divran** [comment]
>Finally no sneaky e2s or other player's shit getting included with a dupe

so you basically made a check for ownership only, ignoring prop protection friends?

**Comment by thegrb93** [comment]
Everything has been working fine so I think it is safe to merge.

**Comment by thegrb93** [comment]
Still no bugs so should be safe.

**Comment by thegrb93** [comment]
Git acting weird. Will remake

**Pull request closed without merging**
