### PR TITLE
Remove unused undo umsg

### PR DESCRIPTION
**Pull request by thegrb93**
Warning: Unhandled usermessage 'Undone'

### CODE REVIEW

**Comment by AbigailBuccaneer** [comment]
Does the fact that this punches `nil` holes in the undo table have any adverse effect? It's not code you wrote, but I do wonder if the umsg was previously used by the `undo` module to keep the client and server happily in sync.

**Comment by bigdogmat** [comment]
In Gmod they switched to net messages using the `Undo_Undone` name. Still using a 16 bit int.

**Comment by AbigailBuccaneer** [comment]
Thanks for digging that out, @bigdogmat. So it looks like this pull request isn't a suitable fix.

It'd be worth also making a pull request against Garry's Mod to add an `undo.Remove(player, index)` function so that we don't have to reimplement internals of the undo module.

**Comment by thegrb93** [comment]
Fixed

**Comment by AbigailBuccaneer** [comment]
Can we have comments explaining that this is to mirror the internal behaviour of Garry's `undo` module, so that next time it changes and breaks we know why this code is here?

**Comment by thegrb93** [comment]
k

**Pull request merged**
