### PR TITLE
Fix area copy.

### PR DESCRIPTION
**Pull request by thegrb93**
FindInBox can only return a max of 512 entities.

### CODE REVIEW

**Comment by Divran** [comment]
garry pls

**Comment by thegrb93** [comment]
k

**Comment by thegrb93** [comment]
Ready to merge when you are

**Comment by thegrb93** [comment]
I'm going to assume this will be merged and go ahead an get it merged with the world_copy branch because there's going to be some conflicts. This is ready to merge though.

**Pull request merged**
