### PR TITLE
Attempts to fix issues #389

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by thegrb93** [comment]
Please revert all the var name changes and parentheses added to if statements and i'll review

**Comment by dvdvideo1234** [comment]
Hello, @thegrb93.

Thanks! Done!

**Comment by thegrb93** [comment]
Yes, please undo those.

**Comment by dvdvideo1234** [comment]
> Yes, please undo those.

I will remove the main `()` on every IF statement

**Comment by thegrb93** [comment]
Only ones you added please

**Comment by thegrb93** [comment]
Nobody wants to review 300 lines

**Comment by thegrb93** [comment]
Better yet, remove all the cleanup from this PR and put them in a different PR.

**Comment by dvdvideo1234** [comment]
@thegrb93

> You can put the cleanup changes in another PR if you want.

Done ;)

**Comment by thegrb93** [comment]
This doesn't fix #374 so I'm removing that from the title.

**Comment by thegrb93** [comment]
Infact, it looks like the current version of CheckValidDupe already checks headent.Z now https://github.com/wiremod/advdupe2/blob/41023f7e7fd0f209281334bb28d01e32f6ef67b3/lua/advdupe2/sh_codec.lua#L421

**Comment by dvdvideo1234** [comment]
This is just for checks in the tool for spawning stuff defaults Z to zero. The user had trouble with pasting an old dupe where such value did not exist ;) I've already checked `Edit by maintainers`, so you are able you commit stuff yourself ;)

**Comment by dvdvideo1234** [comment]
@thegrb93 It has been one month xD

**Comment by wrefgtzweve** [comment]
> This is just for checks in the tool for spawning stuff defaults Z to zero. The user had trouble with pasting an old dupe where such value did not exist ;) I've already checked `Edit by maintainers`, so you are able you commit stuff yourself ;)

Yeah we're still getting errors for that multiple times per week, it'd be cool if this pr could be merged.

**Comment by thegrb93** [comment]
I'm not reviewing style changes with code changes. Fix the bug and do your style changes in separate PRs please.

**Comment by dvdvideo1234** [comment]
@thegrb93 So can I just delete this commit https://github.com/wiremod/advdupe2/pull/399/commits/c743261eee8763592c569ccf5f561dddbddf0d3d by force pushing or should I make new PR ?

**Comment by thegrb93** [comment]
I don't like any of the code changes mixed with the style changes. That's why its been open for so long.

**Comment by thegrb93** [comment]
Read the comments at the top of the page. Putting code changes and lots of style changes together makes verifying code consistency too hard to bother with.

**Comment by dvdvideo1234** [comment]
I'll just make another PR tomorrow

**Pull request closed without merging**
