### PR TITLE
Undo fix

### PR DESCRIPTION
**Pull request by thegrb93**
Fixes lua error that occurs when undoing while pasting.

### CODE REVIEW

**Comment by thegrb93** [comment]
Damnit git, I didn't want those other commits in this pr.

**Comment by thegrb93** [comment]
Fixed it with a rebase

**Comment by thegrb93** [comment]
There error is caused by this https://github.com/garrynewman/garrysmod/blob/ead2b4d7f05681e577935fef657d4a4d962091e6/garrysmod/lua/includes/modules/undo.lua#L369

**Comment by AbigailBuccaneer** [comment]
Good catch. Presumably `Player.AdvDupe2.Name` isn't allowed any quotation marks in it?

**Comment by thegrb93** [comment]
Merge soon?

**Comment by Divran** [comment]
uhh yeah how did that even cause an error in the first place

**Comment by AbigailBuccaneer** [comment]
@Divran the custom undo text is eventually sent via `Player:SendLua`, and so if it contains quotation marks then the Lua is invalid.

**Comment by AbigailBuccaneer** [comment]
Somebody should check that `Player.AdvDupe2.Name` can't have quotation marks in it, but this itself is a sensible change to merge.

**Pull request merged**
