### PR TITLE
New encoder

### PR DESCRIPTION
**Pull request by thegrb93**
Closes: #203

### CODE REVIEW

**Comment by thegrb93** [comment]
Will compare performance tomorrow.

**Comment by thegrb93** [comment]
NEW
Encode: 0.021351500000037
Decode: 0.35379859999989


OLD
Encode: 0.049334999999928
Decode: 17.431951

**Comment by thegrb93** [comment]
Made an 8000 entity dupe

NEW
Decode: 0.54760260000057
Encode: 1.3525143999996

OLD
Decode: 1.4809618999998
Encode: 1.3172728999998

Going to need to make the encoder/decoder coroutined.

**Comment by thegrb93** [comment]
May not seem like much of an improvement, but that's because the dupe has lots of doubles. Dupes with lots of string data will be significantly faster.

**Comment by thegrb93** [comment]
Also I forgot to mention I'm using an extremely fast SSD which makes the filebuffer much faster.

**Comment by thegrb93** [comment]
Need to compare fidelity and then do threading.

**Comment by RoofLee** [comment]
Cool

**Comment by thegrb93** [comment]
This should just be a module. Performance is not as good as I hoped.

**Pull request closed without merging**
