### PR TITLE
Fixed: AdvDupe2 Shows the name of the spawned contraption in the undo…

### PR DESCRIPTION
**Pull request by dvdvideo1234**
… list

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
image

**Comment by dvdvideo1234** [comment]
Is there a point for this to be done for other `undo.Create`-s ?

**Comment by dvdvideo1234** [comment]
Logs:  [log.txt](https://github.com/wiremod/advdupe2/files/6743263/log.txt)

**Comment by thegrb93** [comment]
Should probably match what's in 'SetCustomUndoText'

**Comment by dvdvideo1234** [comment]
Calling of [`undo.SetCustomUndoText`][ref-ut] changes the player [notification](https://wiki.facepunch.com/gmod/Enums/NOTIFY) when the duplication is undone, rather than ['undo.Create '][ref-cr] which creates the undo entry with the specified name as string. If [`undo.SetCustomUndoText`][ref-ut] is not called, the undo notification will take its message from ['undo.Create '][ref-cr].

[ref-ut]: https://wiki.facepunch.com/gmod/undo.SetCustomUndoText
[ref-cr]: https://wiki.facepunch.com/gmod/undo.Create

**Pull request merged**
