### PR TITLE
Add player to AdvDupe_FinishPasting(the other one)

### PR DESCRIPTION
**Pull request by Weol**
Would allow developers to keep track of players' advanced duplicated entities.

### CODE REVIEW

**Comment by Divran** [comment]
don't we already have this

**Comment by Weol** [comment]
Yeah, I noticed that after an hour trying to figure out why the first one didn't pass along the player. Seems to me like the first one isn't ever used, maybe just in special cases.

**Comment by thegrb93** [comment]
It looks like AdvDupe2.duplicator.Paste is used for when the map dupe file is being pasted when the server loads. It seems to also be used by the contraption spawner. The different between it and the normal pasting is that it pastes everything instantly while the other one pastes over time.

**Comment by AbigailBuccaneer** [comment]
Well, this is indicative of larger problems with AdvDupe2, but this PR does make the code less broken so I'm merging it.

**Pull request merged**
