### PR TITLE
PR for code reorder and factorization. Must not change behavior

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by thegrb93** [comment]
White space changes only allowed. And do not change `T[#T +1] =` into `table.insert(T`

**Comment by dvdvideo1234** [comment]
Will revert the [#T + 1] tomorrow. Accidentally saved with spaces and reverted to tabs.

**Comment by dvdvideo1234** [comment]
I do not change any functionality... This was the goal, was it not ?
The new code is only New function for the console variables and box check. There is literally no new code

**Comment by thegrb93** [comment]
That's not the point. The point is somebody has to read the changes to make sure they are good and adding hundreds of little format changes in it makes it much more painful.

Separating the whitespace changes and code changes allows reviewers to let the `-w` flag of git do most of the work verifying that the whitespace changes are consistent.

**Comment by dvdvideo1234** [comment]
Yeah.. I am using this
image

**Comment by thegrb93** [comment]
Many organizations outright reject these kinds of refactors because it's too easy to sneak in malicious changes under the guise of cleanup.

**Comment by dvdvideo1234** [comment]
How should  split it up ?
For example:
1. Make PR with only the white-space formatted file
2. After commit replace with deducted functions file

Hmm doubt that multi-line IF statements is malicious though?

**Comment by thegrb93** [comment]
1. Many people will have disagreements with what formats look better. I myself disagree with lots of these format changes.
2. To most people it is just a waste of time.

Here's a few of the format changes I disagree with:
Variable name abbreviations
Multi-lining if statements that look much better as a single line
Breaking single lines of code into its own functions

I GUESS I can live with whitespace changes existing in this PR, but the rest of those things are making me want to close it.

**Comment by dvdvideo1234** [comment]
Ah, so it seems the PR is pointless.

**Pull request closed without merging**
