### PR TITLE
[WIP] Fix coding style

### PR DESCRIPTION
**Pull request by AvarianKnight**
Fix coding style to be in line with https://github.com/wiremod/wire/wiki/Coding-style

### CODE REVIEW

**Comment by thegrb93** [comment]
Any chance you can wait until https://github.com/wiremod/advdupe2/pull/221 is ready first?

This is going to conflict hard

**Comment by AvarianKnight** [comment]
Yea, no problem.

**Comment by thegrb93** [comment]
You're free to do this whenever now. I'm done refactoring, just bugfixes left.

**Comment by thegrb93** [comment]
I guess re-open when you're ready

**Pull request closed without merging**
